<?php
/**
 * Simple Theme: wp_body_open Hook.
 * 
 * https://developer.wordpress.org/reference/functions/wp_body_open/
 */

/**
 * Used for remove SVG generated by WordPress.
 * 
 * https://stackoverflow.com/questions/71290047/how-to-remove-front-svg-in-wordpress-5-9-version
 */
remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );
